### ISSUE TITLE
why not zbus

### ISSUE THREAD

**Issue by WenTao-Love** [akullpp/awesome-java#384]
ZBUS=MQ+RPC, an extremely light-weighted(~300K) Service Bus focus on Message Queue, Remote Procedure Call, HTTP MicroService, capable of tackling DMZ network constrains, with multiple languages(Java/C#/C/Python/Javascript) support. http://zbus.org 
!!!!!!

**Comment by jbduncan** [comment]
I can't speak on behalf of @akullpp, but I know for me at least, I'd struggle to consider zbus for inclusion in awesome-java, because your link currently leads to a non-English website, meaning I can't understand what zbus is about without using Google Translate (which isn't 100% reliable even at the best of times).

Does zbus have an proper English website we can refer to?

**Comment by jbduncan** [comment]
Not to mention, even when I use Google Translate myself, the website is... barebones, to say the least.

**Comment by akullpp** [comment]
As @jbduncan mentioned I don't add sites that cater only to specific language speakers (Chinese the most common example). English is the lingua franca.
