### ISSUE TITLE
Nice list!!

### ISSUE THREAD

**Issue by shavo007** [akullpp/awesome-java#389]
I am not creating a pull request. Just wanted to highlight and mention some possible changes:

+1 for restAssured, really like it for integration tests in a spring boot app
+1 for lombok, makes pojo look so much cleaner

Changes:
For geospatial, elasticsearch (built on top of apache lucene)? geo distance query is lightning fast compared to GIS functions in a relational DB.

Caching: Jedis?
Rest frameworks:Spring Boot?
PDF:iText?
Logging:FileBeats from elastic?

AWS Java SDK for all its services?

Regards,
Shane.

**Comment by akullpp** [comment]
Thank you. However, I don't understand what you suggest. The libraries you mentioned are always included aren't they? Could you please elaborate?

**Comment by shavo007** [comment]
Hi,

I dont see those libraries under the sections i suggested:

Geospatial: Elasticsearch
Caching: Jedis
 Rest frameworks:Spring Boot
PDF:iText
Logging:FileBeats from elastic

Thanks,
Shane.

**Comment by akullpp** [comment]
1. Elasticsearch is not a dedicated geospatial therefore a change of categories doesn't apply.
2. Jedis is a Redis client not a library for caching.
3. Spring Boot is not a REST framework. It is a web framework.
4. iText is already included in the PDF section
5. I don't know if `Filebeat` has a Java API or if it is just written in Java and therefore wouldn't qualify for this list.

**Comment by shavo007** [comment]
Elasticsearch has extremely powerful geospatial lookups unless you are categorising that section just for databases?
Redis is a cache that is one of the engine options for aws elasticache. Jedis is a valid framework in my eyes.
Your right, i missed itext!
True, filbeats is written in go i believe, and doesnt qualify. But is logstash written in java?

**Comment by akullpp** [comment]
1. ES: Sure it has this functionality but does one functionality suffice the change from a more abstract category to the specific category? 
2. Jedis is already included. It is not a framework. It is a client for Reddis. Side note: Reddis is not a  cache.
3. Logstash is already included.

Please have a look at the existing list before recommending already included entries.

**Comment by shavo007** [comment]
FYI,  redis and is a cache solution for aws elasticache. http://docs.aws.amazon.com/AmazonElastiCache/latest/UserGuide/Clusters.Create.Redis.CON.html

**Comment by jbduncan** [comment]
@shavo007, according to the redis website <http://redis.io/>, redis is an "in-memory data structure store, used as database, cache and message broker", which sounds more generic to me than a cache (or indeed a database). So I'd argue that, if Jedis should be moved elsewhere, it should go under **Data structures**.

FYI, I'm the pull requester/creator of the **Caching** section - my reason for adding it to awesome-java at the time was I because wanted to share Caffeine, but I didn't feel that the other sections were good places to put Caffeine under - so my opinion regarding Jedis is most likely biased. :smiley:

See my original PR here: <https://github.com/akullpp/awesome-java/pull/382/files>
