### ISSUE TITLE
Ancients

### ISSUE THREAD

**Issue by akullpp** [akullpp/awesome-java#410]
See discussion in #94.

> The scope of awesome should probably not include outdated (e.g. Velocity) or highly disregarded frameworks (e.g. JSF)

How do we handle these frameworks?

**Comment by jbduncan** [comment]
We could put a tiny legend (or equivalent section) towards the top of the README.

In my mind, it would have symbols like :star: and :x: (with brief descriptions saying that :star: means a project/framework is **awesome** and :x: means it's "ancient" or otherwise listed only for historical purposes and should be avoided in new code).

One would then label each project in the rest of the README with the appropriate symbol.

If using just 2 symbols is not sufficient to describe all the different types of **awesome** and "ancient"/undesirable/outdated projects, we could always add more to the legend.

Indeed, if :star: and :x: are not very good choices, we could go as far as considering other emojis.

**Comment by jbduncan** [comment]
An alternative approach could be to append each project name with a single word describing it's level of awesomeness.

E.g. if we consider the **Build** section, it may become something like this:


## Build

*Tools which handle the build cycle and dependencies of an application.*

* [Apache Ant](http://ant.apache.org/) _(ancient)_ - Build process management with XML.
* [Apache Maven](http://maven.apache.org/) _(awesome)_ - Declarative build and dependency management which favors convention over configuration. It might be preferable to Apache Ant which uses a rather procedural approach and can be difficult to maintain.
* [Bazel](http://bazel.io) _(awesome)_ - Build tool from Google that builds code quickly and reliably.
* [Gradle](http://gradle.org/) _(awesome)_ - Incremental builds which are programmed via Groovy instead of declaring XML. Works well with Maven's dependency management.

**Comment by jbduncan** [comment]
@akullpp, what are your thoughts regarding what I've suggested?

**Comment by akullpp** [comment]
I would only mark specific libraries with an icon. Dividing the entries in two clusters and adding icons accordingly would make the list look bloated.

Also it is implied that every library in the list is some kind of 'awesome'. 😄

**Comment by jbduncan** [comment]
Okay, your comment regarding marking specific libraries makes sense to me. :smile:

Apologies if I gave the impression that we should split the list into two clusters. What I had meant to say was that, somewhere in the list, maybe the top or the bottom, we should have a tiny 'legend' (in the Microsoft Excel sense, rather than legendary sense), and in this legend there would be e.g. two icons with corresponding descriptions:

- :star: - An awesome, shiny new project!
- :computer: - An outdated but otherwise enduring and awesome project!

Although, your earlier comment has convinced me that a :star: entry is simply not needed. Perhaps instead we could add the 'commercial' icon like the one you made for the awesome commercial projects in the list. Perhaps in the legend it could be accompanied with a description like 'An awesome closed-source commercial project!'.

**Comment by akullpp** [comment]
Ancients have been completely removed. It makes no sense to keep them if there are better tools with at least the same scope.
