### ISSUE TITLE
Better descriptions

### ISSUE THREAD

**Issue by akullpp** [akullpp/awesome-java#91]
The descriptions are often times non-existing or bad. It needs to be clear how one item in a list differs from another. What are the particular advantage of the item in regard to others.

Example section: Continuous Integration

**Comment by akullpp** [comment]
PRs welcome.

**Comment by JerJohn15** [comment]
@akullpp, Although now it seems as though most of the resources included on this list have a description on them, I do agree with you that there  needs to be a distinction between what each reference does and why it is worth viewing. This should be included in the guidelines and not be allowed as an accepted PR from users otherwise.

**Comment by akullpp** [comment]
Added to contribution guidelines in d4406a3e1e.

The existing descriptions need to be improved though and PRs are welcome.
